package rater

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"
)

const (
	defaultLLMBaseURL          = "https://api.openai.com/v1"
	envLLMScoreFile            = "SAFESPACE_LLM_SCORE_FILE"
	envLLMOpenAIFallbackSwitch = "SAFESPACE_LLM_OPENAI_FALLBACK"
)

// RuntimeLLMScoreConfig stores skill-level LLM score decisions generated by skill runtime/model orchestration.
type RuntimeLLMScoreConfig struct {
	Default *LLMScoreResult           `json:"default,omitempty"`
	Skills  map[string]LLMScoreResult `json:"skills,omitempty"`
}

type RuntimeScoreFileLLMScorer struct {
	path         string
	defaultScore *LLMScoreResult
	skills       map[string]LLMScoreResult
}

type OpenAICompatibleLLMScorer struct {
	endpoint string
	apiKey   string
	model    string
	client   *http.Client
}

// NewRuntimePreferredLLMScorer resolves scorer order:
// 1) runtime score file from explicit path / SAFESPACE_LLM_SCORE_FILE
// 2) OpenAI-compatible fallback only when SAFESPACE_LLM_OPENAI_FALLBACK=1
// 3) nil scorer (rule-only)
func NewRuntimePreferredLLMScorer(explicitScoreFile string) (LLMScorer, error) {
	scoreFile := strings.TrimSpace(explicitScoreFile)
	if scoreFile == "" {
		scoreFile = strings.TrimSpace(os.Getenv(envLLMScoreFile))
	}
	if scoreFile != "" {
		return NewRuntimeScoreFileLLMScorer(scoreFile)
	}

	if strings.TrimSpace(os.Getenv(envLLMOpenAIFallbackSwitch)) != "1" {
		return nil, nil
	}
	return NewEnvLLMScorer(), nil
}

func NewRuntimeScoreFileLLMScorer(path string) (LLMScorer, error) {
	cleanPath := strings.TrimSpace(path)
	if cleanPath == "" {
		return nil, fmt.Errorf("score file path is required")
	}
	absPath, err := filepath.Abs(cleanPath)
	if err == nil {
		cleanPath = absPath
	}

	buf, err := os.ReadFile(cleanPath)
	if err != nil {
		return nil, fmt.Errorf("read runtime score file failed: %w", err)
	}

	cfg := RuntimeLLMScoreConfig{}
	if err := json.Unmarshal(buf, &cfg); err != nil {
		return nil, fmt.Errorf("parse runtime score file failed: %w", err)
	}

	skills := make(map[string]LLMScoreResult, len(cfg.Skills))
	for k, v := range cfg.Skills {
		skillID := strings.TrimSpace(k)
		if skillID == "" {
			continue
		}
		skills[skillID] = LLMScoreResult{
			Score:  clampScore(v.Score),
			Model:  strings.TrimSpace(v.Model),
			Reason: strings.TrimSpace(v.Reason),
		}
	}

	var defaultResult *LLMScoreResult
	if cfg.Default != nil {
		v := *cfg.Default
		defaultResult = &LLMScoreResult{
			Score:  clampScore(v.Score),
			Model:  strings.TrimSpace(v.Model),
			Reason: strings.TrimSpace(v.Reason),
		}
	}

	return &RuntimeScoreFileLLMScorer{path: cleanPath, defaultScore: defaultResult, skills: skills}, nil
}

func (s *RuntimeScoreFileLLMScorer) Score(audit SkillAudit) (LLMScoreResult, error) {
	if s == nil {
		return LLMScoreResult{}, fmt.Errorf("runtime score file scorer is nil")
	}
	skillID := strings.TrimSpace(audit.SkillID)
	if skillID != "" {
		if v, ok := s.skills[skillID]; ok {
			return v, nil
		}
	}
	if s.defaultScore != nil {
		return *s.defaultScore, nil
	}
	return LLMScoreResult{}, fmt.Errorf("runtime score not found for skill: %s", audit.SkillID)
}

func NewEnvLLMScorer() LLMScorer {
	model := strings.TrimSpace(os.Getenv("SAFESPACE_LLM_MODEL"))
	apiKey := strings.TrimSpace(os.Getenv("SAFESPACE_LLM_API_KEY"))
	if model == "" || apiKey == "" {
		return nil
	}
	base := strings.TrimSpace(os.Getenv("SAFESPACE_LLM_BASE_URL"))
	if base == "" {
		base = defaultLLMBaseURL
	}
	timeout := 12 * time.Second
	if raw := strings.TrimSpace(os.Getenv("SAFESPACE_LLM_TIMEOUT_MS")); raw != "" {
		if ms, err := strconv.Atoi(raw); err == nil && ms > 0 {
			timeout = time.Duration(ms) * time.Millisecond
		}
	}

	return &OpenAICompatibleLLMScorer{
		endpoint: strings.TrimRight(base, "/") + "/chat/completions",
		apiKey:   apiKey,
		model:    model,
		client:   &http.Client{Timeout: timeout},
	}
}

func (s *OpenAICompatibleLLMScorer) Score(audit SkillAudit) (LLMScoreResult, error) {
	if s == nil {
		return LLMScoreResult{}, fmt.Errorf("llm scorer is nil")
	}
	prompt := buildLLMAuditPrompt(audit)
	body := map[string]any{
		"model":       s.model,
		"temperature": 0,
		"messages": []map[string]string{
			{"role": "system", "content": "You are a strict code security reviewer. Return only compact JSON with keys score (0-100 number) and reason (string <= 120 chars)."},
			{"role": "user", "content": prompt},
		},
	}
	buf, _ := json.Marshal(body)
	req, err := http.NewRequest(http.MethodPost, s.endpoint, bytes.NewReader(buf))
	if err != nil {
		return LLMScoreResult{}, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+s.apiKey)

	resp, err := s.client.Do(req)
	if err != nil {
		return LLMScoreResult{}, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		var er map[string]any
		_ = json.NewDecoder(resp.Body).Decode(&er)
		return LLMScoreResult{}, fmt.Errorf("llm scoring failed: status=%d error=%v", resp.StatusCode, er["error"])
	}

	var payload struct {
		Model   string `json:"model"`
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&payload); err != nil {
		return LLMScoreResult{}, err
	}
	if len(payload.Choices) == 0 {
		return LLMScoreResult{}, fmt.Errorf("llm response missing choices")
	}
	content := strings.TrimSpace(payload.Choices[0].Message.Content)
	score, reason, err := parseLLMScoreContent(content)
	if err != nil {
		return LLMScoreResult{}, err
	}
	model := strings.TrimSpace(payload.Model)
	if model == "" {
		model = s.model
	}
	return LLMScoreResult{Score: score, Model: model, Reason: reason}, nil
}

func buildLLMAuditPrompt(a SkillAudit) string {
	return fmt.Sprintf("skill_id=%s\nrule_score=%.1f\nrisk_high=%d\nrisk_medium=%d\nrisk_low=%d\nrisks=%s\nstrengths=%s\nPlease provide conservative security score.",
		a.SkillID,
		a.RuleScore,
		a.RiskHigh,
		a.RiskMedium,
		a.RiskLow,
		strings.Join(a.Risks, " | "),
		strings.Join(a.Strengths, " | "),
	)
}

func parseLLMScoreContent(content string) (float64, string, error) {
	clean := strings.TrimSpace(content)
	clean = strings.TrimPrefix(clean, "```json")
	clean = strings.TrimPrefix(clean, "```")
	clean = strings.TrimSuffix(clean, "```")
	clean = strings.TrimSpace(clean)

	var parsed struct {
		Score  float64 `json:"score"`
		Reason string  `json:"reason"`
	}
	if err := json.Unmarshal([]byte(clean), &parsed); err == nil {
		return clampScore(parsed.Score), truncateRunes(strings.TrimSpace(parsed.Reason), 120), nil
	}

	re := regexp.MustCompile(`(?i)score\s*[:=]\s*([0-9]+(?:\.[0-9]+)?)`)
	match := re.FindStringSubmatch(clean)
	if len(match) >= 2 {
		v, err := strconv.ParseFloat(match[1], 64)
		if err == nil {
			return clampScore(v), truncateRunes(clean, 120), nil
		}
	}

	return 0, "", fmt.Errorf("cannot parse llm score content")
}
